apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-todo
  template:
    metadata:
      labels:
        app: react-todo
    spec:
      containers:
      - name: react-todo-app
        # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
        # Replace $GCLOUD_PROJECT with your project ID.
        image: us-east4-docker.pkg.dev/cisc5550-430923/flask-ims/react-todo-gke:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 80
        env:
          - name: PORT
            value: "80"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"